function [im_x, im_y] = project(camera, world_X, world_Y, world_Z)

    z = camera.P(3, 1) * world_X ...
        + camera.P(3, 2) * world_Y ...
        + camera.P(3, 3) * world_Z ...
        + camera.P(3, 4);
    
    im_x = round((camera.P(1, 1) * world_X ...
        + camera.P(1, 2) * world_Y ...
        + camera.P(1, 3) * world_Z ...
        + camera.P(1, 4)) ./ z);
    
    im_y = round((camera.P(2, 1) * world_X ...
        + camera.P(2, 2) * world_Y ...
        + camera.P(2, 3) * world_Z ...
        + camera.P(2, 4)) ./ z);